name: build
on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: kaka
    strategy:
      matrix:
        platform:
          - linux/amd64
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: docker/setup-buildx-action@v3
      - name: demo
        run: |
          echo "hello in build"
          ps
          whoami
          ls /
          ls ~/